
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Kristen Moore  ## put your name
title: 'Data Scientist'  ## your title
location: Melbourne, Aus


## Social Profiles
linkedin: http://www.linkedin.com  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
